version: '3'

services:
  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx:stable
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - express

  express:
    container_name: express
    hostname: express
    image: node:14.16.1-alpine
    ports:
      - 3000:3000
    volumes:
      - .:/src
    working_dir: /src
    command: [sh, -c, npm install && npm run build && npm run start]
